### ISSUE TITLE
Error creating process c:\Windows\SysWOW64\notepad.exe with working directory test.txt

### ISSUE THREAD

**Issue by pkxpp** [lukedodd/Heapy#4]
when I run the commond:
`>Heapy_x64.exe c:\Windows\SysWOW64\notepad.exe test.txt`
there is a error:
`Error creating process c:\Windows\SysWOW64\notepad.exe with working directory test.txt`

ps:
my system is win7

**Comment by lukedodd** [comment]
Are you using the latest version? The output above suggests not.

 - The latest version is not available in a prebuilt form. I need to update the blog post and the builds!
 - The new versions handle working directories differently.
 - The Readme.txt (in the release, or CreateReelase/Readme.txt) has not been updated to reflect the changes in the new version.
 - The Readme.txt also contains a mistake with the notepad example - SysWOW64/notepad.exe is actually 32 bit notepad, System32/notepad.exe is actually the 64 bit version.

If I clone the project to x:/Heapy, compile in visual studio, run x:/CreateRelease/CreateRelease.bat then the following works:

```
X:\Heapy\dist>Heapy_Win32.exe c:\Windows\SysWOW64\notepad.exe
Starting process with heap profiling enabled...
Target exe path: c:\Windows\SysWOW64\notepad.exe
Target execommand line: c:\Windows\SysWOW64\notepad.exe
Dll to inject: X:\Heapy\dist\HeapyInject_Win32.dll

X:\Heapy\dist>Heapy_x64.exe C:\Windows\System32\notepad.exe
Starting process with heap profiling enabled...
Target exe path: C:\Windows\System32\notepad.exe
Target execommand line: C:\Windows\System32\notepad.exe
Dll to inject: X:\Heapy\dist\HeapyInject_x64.dll

```

And the HeapyProfile.txt contains what I expect.

**Comment by lukedodd** [comment]
If you need a prebuilt exe shoot me an email.

**Comment by lukedodd** [comment]
Okay I just fixed the readme and put a new release here: https://github.com/lukedodd/Heapy/releases

Reopen if you still have issues.
